/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Account: typeof import('./src/components/Login/account.vue')['default']
    AtionBar: typeof import('./src/components/Editor/AtionBar/index.vue')['default']
    BarEchart: typeof import('./src/components/Echarts/src/BarEchart.vue')['default']
    Dropdown: typeof import('./src/components/Header/Dropdown/index.vue')['default']
    Editor: typeof import('./src/components/Editor/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Form: typeof import('./src/components/Form/index.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    Menus: typeof import('./src/components/Menus/index.vue')['default']
    Modal: typeof import('./src/components/Modal/index.vue')['default']
    Phone: typeof import('./src/components/Login/phone.vue')['default']
    PieEchart: typeof import('./src/components/Echarts/src/PieEchart.vue')['default']
    RoseEchart: typeof import('./src/components/Echarts/src/RoseEchart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search/index.vue')['default']
    Tab: typeof import('./src/components/Header/Tab/index.vue')['default']
    Table: typeof import('./src/components/Table/index.vue')['default']
  }
}
